name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Checkout repo
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Verify Node.js Version
        run: node -v
        
      - name: Download cortexcli
        env:
          CORTEX_API_KEY: ${{secrets.CORTEX_API_KEY}}
          CORTEX_API_KEY_ID: ${{secrets.CORTEX_API_KEY_ID}}
          CORTEX_API_URL: "https://api-tac-c3.xdr.eu.paloaltonetworks.com"
        run: |
          set -x
          crtx_resp=$(curl "${CORTEX_API_URL}/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
            -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" \
            -H "Authorization: ${CORTEX_API_KEY}")
          crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
          curl -o cortexcli $crtx_url
          chmod +x cortexcli
          ./cortexcli --version
          
      - name: Run Cortex CLI Code Scan
        env:
          CORTEX_API_KEY: ${{secrets.CORTEX_API_KEY}}
          CORTEX_API_KEY_ID: ${{secrets.CORTEX_API_KEY_ID}}
          CORTEX_API_URL: "https://api-tac-c3.xdr.eu.paloaltonetworks.com"
        run: |
          ./cortexcli \
            --api-base-url "${CORTEX_API_URL}" \
            --api-key "${CORTEX_API_KEY}" \
            --api-key-id "${CORTEX_API_KEY_ID}" \
            code scan \
            --directory "${{github.workspace}}" \
            --repo-id "${{github.repository}}" \
            --branch "${{github.ref_name}}" \
            --source "GITHUB_ACTIONS" \
            --create-repo-if-missing
    
      - run: echo "🍏 This job's status is ${{ job.status }}."

      
